#!/usr/bin/env bash
# Generate the lab's local CA, TLS and signing certificates, and random
# secrets in .env. Safe to re-run: existing secrets are kept, certificates
# are only reissued when missing, near expiry, or LAB_HOST has changed.
#
#   scripts/setup.sh                      # first run, LAB_HOST=idlab.home
#   LAB_HOST=localhost scripts/setup.sh   # e.g. in CI
#   scripts/setup.sh --rotate             # new random value for every secret in .env
#                                         # (then: scripts/test.sh --fresh)
#   scripts/setup.sh --force              # regenerate CA, keys and secrets (then: scripts/test.sh --fresh)
#
# Nothing secret is ever printed. Read values from .env when you need them.
source "$(dirname "$0")/lib.sh"
require openssl docker date base64

FORCE=0 ROTATE=0
case "${1:-}" in
  "")       ;;
  --force)  FORCE=1 ;;
  --rotate) ROTATE=1 ;;
  *) die "unknown option: $1 (use --rotate or --force)" ;;
esac

rand() { openssl rand -base64 48 | tr -dc 'A-Za-z0-9' | head -c "${1:-32}"; }

# Value from an existing .env, without sourcing it.
existing() { [[ -f "$ENV_FILE" ]] && sed -n "s/^$1=//p" "$ENV_FILE" | tail -n1 || true; }

if (( FORCE )); then
  warn "--force: regenerating CA, certificates and all secrets"
  warn "existing Keycloak data will not match; run 'scripts/test.sh --fresh' afterwards"
  rm -rf "$CERTS_DIR" "$ENV_FILE"
fi

LAB_HOST="${LAB_HOST:-$(existing LAB_HOST)}"
LAB_HOST="${LAB_HOST:-idlab.home}"
[[ "$LAB_HOST" =~ ^[A-Za-z0-9.-]+$ ]] || die "LAB_HOST must be a DNS name, got: $LAB_HOST"

mkdir -p "$CERTS_DIR" "$STATE_DIR/saml-sp"
chmod 700 "$CERTS_DIR"

# --- Local CA ---------------------------------------------------------------
if [[ ! -f "$CERTS_DIR/ca.key" || ! -f "$CERTS_DIR/ca.crt" ]]; then
  log "creating local CA"
  ( umask 077
    openssl req -x509 -new -newkey rsa:3072 -nodes -sha256 -days 3650 \
      -keyout "$CERTS_DIR/ca.key" -out "$CERTS_DIR/ca.crt" \
      -subj "/O=identity-lab/CN=identity-lab Local CA" \
      -addext "basicConstraints=critical,CA:TRUE" \
      -addext "keyUsage=critical,keyCertSign,cRLSign" 2>/dev/null )
  chmod 644 "$CERTS_DIR/ca.crt"
  rm -f "$CERTS_DIR/tls.crt" "$CERTS_DIR/sp-signing.crt"   # force reissue under the new CA
fi

# --- TLS certificate shared by all three services ---------------------------
SAN="DNS:$LAB_HOST,DNS:keycloak,DNS:saml-sp,DNS:oidc-rp,IP:127.0.0.1"
[[ "$LAB_HOST" != "localhost" ]] && SAN="$SAN,DNS:localhost"
needs_tls=0
if [[ ! -f "$CERTS_DIR/tls.crt" ]]; then
  needs_tls=1
elif ! openssl x509 -in "$CERTS_DIR/tls.crt" -noout -checkend $((30*86400)) >/dev/null; then
  needs_tls=1
elif ! openssl x509 -in "$CERTS_DIR/tls.crt" -noout -ext subjectAltName 2>/dev/null \
       | grep -q "DNS:$LAB_HOST\b"; then
  needs_tls=1
fi
if (( needs_tls )); then
  log "issuing TLS certificate for $LAB_HOST"
  issue_cert "$CERTS_DIR/tls" "$LAB_HOST" "-1 hour" "+397 days" server "$SAN"
fi

# --- SAML SP signing certificate ---------------------------------------------
if [[ ! -f "$CERTS_DIR/sp-signing.crt" ]] \
   || ! openssl x509 -in "$CERTS_DIR/sp-signing.crt" -noout -checkend $((30*86400)) >/dev/null; then
  log "issuing SAML SP signing certificate"
  issue_cert "$CERTS_DIR/sp-signing" "saml-sp signing" "-1 hour" "+2 years" signing
fi

# Containers run as the invoking user (LAB_UID), so keys can stay 0600.
chmod 600 "$CERTS_DIR"/*.key

# --- Scenario state -----------------------------------------------------------
# libfaketime offset read by the SAML SP (see scenarios/clock-skew.sh).
[[ -f "$STATE_DIR/saml-sp/faketime.rc" ]] || echo "+0" >"$STATE_DIR/saml-sp/faketime.rc"

# --- .env ---------------------------------------------------------------------
# Keep an existing secret, unless rotating.
keep() {
  local v=""
  (( ROTATE )) || v="$(existing "$1")"
  printf '%s' "${v:-$2}"
}

if (( ROTATE )); then
  log "writing .env with NEW values for every secret (certificates unchanged)"
else
  log "writing .env (existing secrets are kept)"
fi
tmp_env="$(mktemp "$LAB_ROOT/.env.XXXXXX")"
chmod 600 "$tmp_env"
cat >"$tmp_env" <<ENV
# Generated by scripts/setup.sh -- contains secrets, never commit.
# Re-running setup.sh keeps these values; --rotate regenerates them.

LAB_HOST=$LAB_HOST
LAB_UID=$(id -u)

KC_PORT=8180
SAML_SP_PORT=8181
OIDC_RP_PORT=8182

KC_ADMIN_USER=admin
KC_ADMIN_PASSWORD=$(keep KC_ADMIN_PASSWORD "$(rand 32)")
POSTGRES_PASSWORD=$(keep POSTGRES_PASSWORD "$(rand 32)")
DEMO_PASSWORD=$(keep DEMO_PASSWORD "$(rand 20)")
OIDC_CLIENT_SECRET=$(keep OIDC_CLIENT_SECRET "$(rand 40)")
SAML_SP_SECRET_KEY=$(keep SAML_SP_SECRET_KEY "$(rand 48)")
OIDC_RP_SECRET_KEY=$(keep OIDC_RP_SECRET_KEY "$(rand 48)")

# Public certificate (not secret): Keycloak uses it to verify signed AuthnRequests.
SP_SIGNING_CERT=$(cert_b64 "$CERTS_DIR/sp-signing.crt")
ENV
mv "$tmp_env" "$ENV_FILE"

if (( ROTATE )); then
  ok "rotated KC_ADMIN_PASSWORD POSTGRES_PASSWORD DEMO_PASSWORD OIDC_CLIENT_SECRET SAML_SP_SECRET_KEY OIDC_RP_SECRET_KEY"
  warn "the running lab still uses the OLD secrets: the Postgres password, Keycloak admin,"
  warn "demo user passwords and OIDC client secret are only applied when the database is created."
  warn "Recreate the lab now:  scripts/test.sh --fresh   (deletes the Keycloak database volume)"
  exit 0
fi
ok "setup complete for https://$LAB_HOST:8180 (Keycloak), :8181 (SAML SP), :8182 (OIDC RP)"
echo "    Trust $CERTS_DIR/ca.crt in your browser to avoid TLS warnings."
echo "    Demo users alice, bob, carol share DEMO_PASSWORD in .env."
